runtime: custom
env: flex

# Use the same Dockerfile
entrypoint: gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 --certfile certs/cert.pem --keyfile certs/key.pem app:app

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
