services:
  harvtech:
    image: 20191405/techwarriors:slim
    ports:
      # - "5000:5000"
      - "${flask_port}:${flask_port}"
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
